package com.github.kelemen.brazier.ui;

import com.github.kelemen.brazier.minions.Minion;
import javax.swing.JButton;

@SuppressWarnings("serial")
public class PlayableMinionComponent extends javax.swing.JPanel {
    private final MinionComponent minionComponent;

    public PlayableMinionComponent(Minion minion) {
        initComponents();

        minionComponent = new MinionComponent(minion);
        jMinionContainer.add(minionComponent);
    }

    public JButton getAttackButton() {
        return jAttackButton;
    }

    public final void setHighlight(boolean highlighted) {
        minionComponent.setHighlight(highlighted);
    }

    public void setMinion(Minion minion) {
        minionComponent.setMinion(minion);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jAttackButton = new javax.swing.JButton();
        jMinionContainer = new javax.swing.JPanel();

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jAttackButton.setText("Attack");
        jPanel1.add(jAttackButton);

        jMinionContainer.setLayout(new java.awt.GridLayout(1, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMinionContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMinionContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAttackButton;
    private javax.swing.JPanel jMinionContainer;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
