package com.github.kelemen.brazier.ui;

import com.github.kelemen.brazier.cards.Card;
import javax.swing.JButton;

@SuppressWarnings("serial")
public class PlayableCardComponent extends javax.swing.JPanel {
    private final CardComponent cardComponent;

    public PlayableCardComponent(Card card) {
        initComponents();

        cardComponent = new CardComponent(card);
        jCardContainer.add(cardComponent);
    }

    public void setCard(Card card) {
        cardComponent.setCard(card);
    }

    public JButton getPlayButton() {
        return jPlayButton;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCardContainer = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPlayButton = new javax.swing.JButton();

        jCardContainer.setLayout(new java.awt.GridLayout(1, 1));

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jPlayButton.setText("Play");
        jPanel2.add(jPlayButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCardContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCardContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jCardContainer;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jPlayButton;
    // End of variables declaration//GEN-END:variables
}
